apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wage-gap-submit
  namespace: sail-24887a
  labels:
    app.kubernetes.io/component: wage-gap-submit
    app.kubernetes.io/instance: wage-gap-submit
    app.kubernetes.io/name: wage-gap-submit
    app.kubernetes.io/part-of: wage-gap-calculator
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 16-ubi8
    function.knative.dev: 'true'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: '100'
        autoscaling.knative.dev/targetUtilizationPercentage: '70'
        autoscaling.knative.dev/window: 60s
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: wage-gap-submit
        app.kubernetes.io/instance: wage-gap-submit
        app.kubernetes.io/part-of: wage-gap-calculator
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-version: 16-ubi8
    spec:
      containerConcurrency: 0
      containers:
        - env:
            - name: MONGO_URI
              value: 'mongodb://wage-gap-calculator-mongo:27017'
          image: >-
            image-registry.openshift-image-registry.svc:5000/sail-24887a/wage-gap-submit
          imagePullPolicy: Always
          name: wage-gap-submit
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            successThreshold: 1
            tcpSocket:
              port: 0
          resources: {}
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
